### ISSUE TITLE
Cant see or hear people in polyzone interiors

### ISSUE THREAD

**Issue by SirKinu** [AaronWeber53/SRC-RP-Discussions#100]
PDM, Luxury, and any other polyzones seem to be an issue. We should prioritize this

**Comment by AaronWeber53** [comment]
https://forum.cfx.re/t/onesync-people-stuttering-blinking-and-going-invisible-inside-interiors-mlos/778397/10

Note to self to look into this

**Comment by AaronWeber53** [comment]
All interiors fixed
