### ISSUE TITLE
House Decoration

### ISSUE THREAD

**Issue by LibexiL** [AaronWeber53/SRC-RP-Discussions#113]
House Decoration Script works, but with bugs.
> So while using the house decoration script, it works as intended all the way until you fully buy and place the object. After you place your selected the menu completely stops working and is no longer usable. The only way I could think of to fix it is to fly out and back in.

No F8 menu errors.

Edit: To get out of the menu you must use the free cam and go out of building range using your WASD in-between each object.

**Comment by Rordanjeid** [comment]
Implemented a hopeful fix. For the time being, after you buy an object if you hold F5 you will regain your cursor and from their can continue using the decorator in that manner or you can click close.
