### ISSUE TITLE
Porsche 918 Spyder

### ISSUE THREAD

**Issue by BubbaHaywood** [AaronWeber53/SRC-RP-Discussions#123]
The brakes need to be fixed and a custom sound would be nice

**Comment by BubbaHaywood** [comment]
https://www.gta5-mods.com/vehicles/porsche-918-mr6-v8-sound-mod-sp-fivem-add-on
this is the sound i would like added

**Comment by SirKinu** [comment]
Brakes fixed and engine sound updated.  will be live tomorrow
