### ISSUE TITLE
Dodge Viper ACR

### ISSUE THREAD

**Issue by LibexiL** [AaronWeber53/SRC-RP-Discussions#125]
https://cdn.discordapp.com/attachments/927643258761392261/947324984580263936/unknown.png

Has no upgrades besides turbo
Cant change wheels either

**Comment by SirKinu** [comment]
This is an issue that has not been easily solved.  Might be fixed on restart, but if not ill leave this ticket open

**Comment by SirKinu** [comment]
fixed.  I will now be known as the car mod daddy
