### ISSUE TITLE
rs6 avant

### ISSUE THREAD

**Issue by Nolan262** [AaronWeber53/SRC-RP-Discussions#127]
the rs6 has no sound so i found one https://www.gta5-mods.com/vehicles/audi-rs6-avant-c8-sound

**Comment by SirKinu** [comment]
This won't work as it replaces existing GTA files.  Can you find another one that works as an add on?

**Comment by Nolan262** [comment]
ill look

**Comment by SirKinu** [comment]
will be there after restart
