### ISSUE TITLE
Porsche 918 Spyder

### ISSUE THREAD

**Issue by BubbaHaywood** [AaronWeber53/SRC-RP-Discussions#128]
The brakes still aren't good and the control is bad it turns very very wide

**Comment by SirKinu** [comment]
Brakes have been adjusted again.  On paper, they are now twice as effective as they were originally.

**Comment by SirKinu** [comment]
Turning circle has been increased, as well as high speed turning should be slightly better.

**Comment by SirKinu** [comment]
Shits fucked actually. something massively wrong with the handling files.  spending tonight fixing it

**Comment by SirKinu** [comment]
918 is now minty fresh.
