### ISSUE TITLE
Car packs 

### ISSUE THREAD

**Issue by Nolan262** [AaronWeber53/SRC-RP-Discussions#131]
Do u think we could get 2 car packs a week because it'll add more of a variety

**Comment by Envy12345** [comment]
i agree sure man

**Comment by BubbaHaywood** [comment]
I disagree 1 a week is fine

**Comment by BubbaHaywood** [comment]
I agree 2 a week sounds good

**Comment by Rordanjeid** [comment]
Cool, 1 a week it is then…

**Comment by Rordanjeid** [comment]
Tristan and I have discussed, keyword…this should be in discussions not issues lol, we will do 2 pack releases in the future once we grow but for the time being we think it should stay at 1 pack while we are relatively small.

**Comment by SirKinu** [comment]
^^^
