### ISSUE TITLE
Aventador

### ISSUE THREAD

**Issue by Envy12345** [AaronWeber53/SRC-RP-Discussions#136]
does not hold top speed. acceleration is good. and maybe higher top speed

**Comment by Envy12345** [comment]
upon racing the r8 i think top speed should be higher and maybe better acceleration through higher speed
also this https://www.gta5-mods.com/vehicles/gintani-f1-lamborghini-aventador-svj-v12-sound-mod-sp-add-on-fivem

**Comment by SirKinu** [comment]
Speed on the aventador will be better, audi handling is also sorted.  Not going to add that sound as it doesn't sound like an Aventador.  sound of an engine of a smaller displacement and higher rpm.  The sound we have now is very close to the real sound
