### ISSUE TITLE
Racing App

### ISSUE THREAD

**Issue by SirKinu** [AaronWeber53/SRC-RP-Discussions#142]
Update the UI to show only, laps, current time, and best time.

App takes record of your fastest lap when racing, but doesn't count the final lap into this.

**Comment by SirKinu** [comment]
Also the racing app timer is FUCKED.  Timed Bishop while sitting in his car at 2:13, and his timer said 1:47.  Not sure why this is happening.

**Comment by AaronWeber53** [comment]
Updated to show checkpoints if sprint or laps if laps race. Removed current time so new ui just has

- Race Name
- Laps/Checkpoints
- Best Time
- Total Time

**Comment by SirKinu** [comment]
Make option for race creator to delete the race after a certain amount of time.  This will stop from races being unavailable due to players not finishing the race and not leaving the race.

**Comment by AaronWeber53** [comment]
Create /stoplaprace command to do this
