### ISSUE TITLE
f12 

### ISSUE THREAD

**Issue by Envy12345** [AaronWeber53/SRC-RP-Discussions#148]
has the same issue as the laferrari. too much body movement when u turn.

**Comment by SirKinu** [comment]
Should be fixed next restart

**Comment by Envy12345** [comment]
most def not fixed. cars a boat now

**Comment by SirKinu** [comment]
I'll check it out tonight.  Tried a fix last night but it must have made it worse

**Comment by SirKinu** [comment]
fixed on restart
