### ISSUE TITLE
idea for pd 

### ISSUE THREAD

**Issue by bruce-cassidy** [AaronWeber53/SRC-RP-Discussions#157]
i was wondering thooo for pd is there a way to implicate a spawn point so we can fly in directly at pd ?  instead of just last location or your house if that makes sense

**Comment by AaronWeber53** [comment]
There is a way to Log Off directly in the break room if you are using 2 characters. I will look at this as a possibility though

**Comment by bruce-cassidy** [comment]
it was more of a concern that what if we are in a chase with someone on the freeway or mount chiliad or something and our heads pop or something happens well when we fly back in where gona be iin the middle of the free way or whwereever we are chasing people  it would just be more helpfull  if that makes sense
