### ISSUE TITLE
Not accessible

### ISSUE THREAD

**Issue by Dru184** [AaronWeber53/SRC-RP-Discussions#160]
**Explanation**
> After I started cornering, I can't open my pockets, saying it's not accessible. 

**Screenshots**
![a](https://user-images.githubusercontent.com/113656126/190945601-36f1103a-3b74-4ff1-9ac1-85b2de309291.PNG)

**Comment by Rordanjeid** [comment]
Inventory is supposed to be unavailable while corner selling.
