### ISSUE TITLE
ems changes

### ISSUE THREAD

**Issue by bruce-cassidy** [AaronWeber53/SRC-RP-Discussions#162]
1-need different ranking vehicles 
2-needs to be able to have access to pd comms  and same with pd towards ems
3-would be nice to have a heli for emeregency's example if someone needs our help at mt chilliad or something 
4-ems needs there own comms channel aswell just like pd 
5-ems should be able to depot cars just like pd  incase pillbox gets crowded with a bundle of random cars and no one to claim them

**Comment by AaronWeber53** [comment]
Should have access to the helicopter on the top of the hospital. On the main floor go to the elevators and the one at the end of that hall.

**Comment by bruce-cassidy** [comment]
ok so the heli works it was just scuffed for us sorry about that what do you think about the other changes ?

**Comment by AaronWeber53** [comment]
I thought they do have access to comms but I guess not. As for the vehicles we will be looking at getting new custom vehicles with liveries for EMS at some point here and then can set them to be rank specific.

**Comment by AaronWeber53** [comment]
EMS and police should have /dv access but it isn't working as well as for channels they will be open to either that is for police/EMS to determine which is used for what department
