### ISSUE TITLE
Smelting gold

### ISSUE THREAD

**Issue by Dru184** [AaronWeber53/SRC-RP-Discussions#166]
**Explanation**
After smelting some chains, it showed that we can pick up the gold, but it did not show in our pockets. 

**Screenshots**
https://medal.tv/games/gta-v/clips/BMvmsZzE-wT80/d1337vBZOLRL?invite=cr-MSxwZFksMjgyODkyMzEs

**Comment by AaronWeber53** [comment]
Looks like your inventory was too full when you collected. I will look into adding a check though so it doesn't pull if it is too full
