### ISSUE TITLE
Custom shoes for male

### ISSUE THREAD

**Issue by Dru184** [AaronWeber53/SRC-RP-Discussions#178]
**Explanation**
It seems like a part of the custom shoes make the shirts go crazy, custom or not. 

**Screenshots**
https://medal.tv/games/gta-v/clips/CFtVLFKDj0pty/d1337HiYRIVO?invite=cr-MSxEUmEsMjgyODkyMzEs

**Comment by AaronWeber53** [comment]
Yeah this happens when the clothing assets are made for different ped models than the multiplayer ones. These will be removed/replaced at some point
