### ISSUE TITLE
1977 Trans Am

### ISSUE THREAD

**Issue by Nolan262** [AaronWeber53/SRC-RP-Discussions#179]
The acceleration is really slow after i upgraded it could you pls turn it up

**Comment by Rordanjeid** [comment]
I’ll take a look at it but do know that late 70s muscle cars were trash in regards to performance 😂

**Comment by Rordanjeid** [comment]
An upgraded slow car is less slow, not necessarily fast. Leave room for other methods of performance 😉

**Comment by Nolan262** [comment]
i never said make it a tesla roadster just put some balls on dat hoe

**Comment by Rordanjeid** [comment]
I’ve never met a hoe with balls…respectfully

**Comment by SirKinu** [comment]
looks amazing, drives like shit.  Perfect <3
