### ISSUE TITLE
boss mission 

### ISSUE THREAD

**Issue by Nolan262** [AaronWeber53/SRC-RP-Discussions#180]
the sandy boss mission where you retrieve his car when u get in to it doesn't register that you have the car 
![boss](https://user-images.githubusercontent.com/95248001/193173971-25b4765b-b3aa-40df-8552-ef68ed938777.png)

**Comment by AaronWeber53** [comment]
There is a possibility of us removing these single player missions so for right now they are not priority. I recommend doing the party missions and just running solo
