### ISSUE TITLE
g wagster 

### ISSUE THREAD

**Issue by Envy12345** [AaronWeber53/SRC-RP-Discussions#181]
does this have mods? also has it been tuned

**Comment by Envy12345** [comment]
after buying it, it has performance mods, but no cosmetics. tune is fine for performance but the body roll and handling should be checked out

**Comment by SirKinu** [comment]
Denied for the following reason:  "g wagster"

**Comment by Envy12345** [comment]
GOTTA pay respect to bishop some way

**Comment by SirKinu** [comment]
body roll is adjusted. its not a huge difference as the car should have body roll
