### ISSUE TITLE
Smelting at the new mining 

### ISSUE THREAD

**Issue by Envy12345** [AaronWeber53/SRC-RP-Discussions#184]
1 carbon and 1 iron make a steel. and i assume the iron smelt is the same but either u should smelt the raw mats into like 20 to 30. or the amount of raw mats needs to be increased alot. in its current state their is no reason to use the refinery to get mats

**Comment by AaronWeber53** [comment]
Smelting outputs have been adjusted as well as scrapyard has been slightly adjusted as well to make it more balanced between the 2

**Comment by Envy12345** [comment]
crafting should be looked at and reduced
