### ISSUE TITLE
Selling gems 

### ISSUE THREAD

**Issue by Envy12345** [AaronWeber53/SRC-RP-Discussions#187]
their needs to be a legal way to sell them. as of right now u have to go do a legal to then go somewhere illegal. also the auto economy of the market seemed fine at first and then some gems were going for $100.

**Comment by AaronWeber53** [comment]
if you read the help menu it tells you where to sell gems legally. And market now has dynamic selling prices so people can't just sell everything and make bank in one go. Makes you have to think about what and how much you are selling

**Comment by Envy12345** [comment]
after finding the gem dealer his prices should be adjusted because they are the same as the metals. despite them being more tedious to collect and what not

**Comment by Envy12345** [comment]
gold ingots sell more then sapphires and the necklaces and rings and earings all sell for 100 each which makes no sense. i think u guys should flesh it out a bit more

**Comment by AaronWeber53** [comment]
Necklaces and stuff will not change for awhile. This stuff is really tedious to balance since it is used across so many different systems across the server like robberies, crafting, etc so right now they will be lower prices to not be broken
