### ISSUE TITLE
Bro these trucking roots are ASS CHEEKS BRUH

### ISSUE THREAD

**Issue by DuckingSmexy** [AaronWeber53/SRC-RP-Discussions#194]
![image](https://user-images.githubusercontent.com/114429960/194692348-47e13ba5-7961-429f-9148-5ad1b3b9a84d.png)
Like bro wtf? WHY DO YOU WANT ME DRIVING OFFROAD IN A SEMIIIIIIIIIII with 0 traction.

**Comment by Envy12345** [comment]
lmao

**Comment by AaronWeber53** [comment]
I hope you realize that the waypoint paths are not always the best way to get to a location, it is just the game telling you the "shortest route"
