### ISSUE TITLE
AMG gtr black series 

### ISSUE THREAD

**Issue by Envy12345** [AaronWeber53/SRC-RP-Discussions#196]
spins and burns the tires way too much when u accelerate. also should have a tune fairly close to the 488 pista.

![image](https://user-images.githubusercontent.com/81500241/194778317-d5dbe389-2125-4b86-acf7-ee7117b82cbb.png)

![image](https://user-images.githubusercontent.com/81500241/194778305-1598f65f-012e-4304-970f-41598c5c0a2b.png)

**Comment by Envy12345** [comment]
also can u add a sound to it idc which just one yall think fits the car

**Comment by SirKinu** [comment]
On keyboard, the car spins for 1.3 seconds, and on controller you can avoid wheelspin completely.  I've adjusted it slightly so it only spins for .9 seconds now.  Keep in mind the car has over 700hp which is going to spin no matter how good your traction control is.  The top speed and acceleration will be slower on the amg, but they will be closer after restart. also added the slr engine sound
