### ISSUE TITLE
Test drive 

### ISSUE THREAD

**Issue by Nolan262** [AaronWeber53/SRC-RP-Discussions#197]
Pls could you move it to the airport this underground spot sucks balls

**Comment by Rordanjeid** [comment]
We have development plans for the airport. We need tests drives out of the way to be honest.

**Comment by Nolan262** [comment]
then would the racetrack work??

**Comment by Rordanjeid** [comment]
It’s too far away and most folks would fall through the map the first time they use it. Where it’s at now is the best option for now.
