### ISSUE TITLE
BOSS MISSION

### ISSUE THREAD

**Issue by Nolan262** [AaronWeber53/SRC-RP-Discussions#199]
The construction site mission is still broken after u kill the bad guys the mission doesn't move on

**Comment by AaronWeber53** [comment]
If you are talking about the one in the city that I am thinking of it is not an elimination task but you have to hit 3 electrical boxes and steal information, it does not require you to kill the people

**Comment by Nolan262** [comment]
when I hit the boxes they dont go away so the mission doesnt move on

**Comment by AaronWeber53** [comment]
Alright the mission is working now, just a reminder when you have issues use f8 so you can send us the exact mission and task with any errors to help us find the issues faster
