### ISSUE TITLE
Rubber Drop Rates need a Buff and others may need nerfing. 

### ISSUE THREAD

**Issue by Brickedd** [AaronWeber53/SRC-RP-Discussions#42]
Currently testing but some issues have come across in drop rates. Rubber has an extremely low drop chance even for scrapping cars, and i as an admin spawned almost all the cars on the list while in front of the scrapyard. I think cars need a minimum of like 10 rubber and a max of 60 if it maybe a high end car. I think  this is balanced because stealing cars may alert police. i think the recycling center need to be buffed by maybe 5%

**Comment by AaronWeber53** [comment]
Increase chances and yields for both scrapyard and recycle
