### ISSUE TITLE
Weapon weights 

### ISSUE THREAD

**Issue by Rordanjeid** [AaronWeber53/SRC-RP-Discussions#70]
Weapons have 1 as their weight and thus too many can be carried at once. Pistols should be 6 to limit one per glovebox. Long arms should weigh 20 each. Also it would be nice if we could implement a belt for police to wear to buff their inventory to compensate for their cuffs, taser and pistol. Tasers should be 4 to limit 2 per glovebox.

**Comment by AaronWeber53** [comment]
updated
