### ISSUE TITLE
Police MDT

### ISSUE THREAD

**Issue by Brickedd** [AaronWeber53/SRC-RP-Discussions#76]
MDT charges and citations need to be looked through as there is no jail time for murder but there is time for attempted murder. so i can sit down with Aaron (Ray) and get these Straightened out.

**Comment by AaronWeber53** [comment]
I kind of want to add the ability to edit these if you are high tier police as things may change overtime and we want to change sentencing. For the time being we can adjust it manually though. I will get you the full list at some point soon

**Comment by AaronWeber53** [comment]
Updated values
