### ISSUE TITLE
Police Ranks rework

### ISSUE THREAD

**Issue by Brickedd** [AaronWeber53/SRC-RP-Discussions#87]
There is currently 4 ranks for pd and i need 5 preferably. 

Chief
Captain
Lieutenant
Sergeant
Officer

**Comment by AaronWeber53** [comment]
![image](https://user-images.githubusercontent.com/48259219/152354387-59e6912c-cbfd-4105-8640-99d6614a7da7.png)

These are the new ones and salaries. 3250 is around the base 20k an hour paycheck.
Also let me know what weapons/vehicles you want for each rank and I can modify that
