### ISSUE TITLE
possible vehicle changes

### ISSUE THREAD

**Issue by Envy12345** [AaronWeber53/SRC-RP-Discussions#97]
most trucks need 120 space. idk if it would be easy or not do this. you could do it by car class. offroad at 120, super and sport stay the same, muscle 40 or 50, and suvs should be 80, vans should be 120. 

while we dont have many cars get them put into classes S,A,B,C ETC. for example when a S is upgraded it would make it an S+. this would be based off speed. race cars should be X or maybe just R class. this would make organization easier down the road when we do have alot of cars 

maybe an app where u can pay your car payment
tracking a car could be a blinking blip when its in a garage. this or just put the waypoint on the garage its in.

would be cool to be able to buy a semi and trailer with like 500 space, u would need to get a CDL and would cost a decent price.

**Comment by Rordanjeid** [comment]
Almost all of this is a recent discussion we have so you should be seeing this implemented in the near future.

**Comment by AaronWeber53** [comment]
Working on this. Reworking script so cars will have a default trunk space based on vehicle category but we will be able to override on a per car basis if we need to.

**Comment by AaronWeber53** [comment]
I believe Ty had taken care of this
